### ISSUE TITLE
Some secondaries start then fail with filesystem errors on buzz/wtf cluster

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#183]
**Describe the bug**
A number of secondaries fail on startup but it is unclear why. Creating a new secondary through the registrar website works just fine so suspect config but cannot see anything obvious with docker service inspect.

**To Reproduce**
1. First these are the secondaries that constantly restart they are scaled back for now to help troubleshooting

```root@buzz-01:~# docker service ls |grep 0/0
q7yik6rzb4fo        2bf9bd8c-ac22-550a-8de9-b25a3c5ca1e5_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:2670->2670/tcp
uyfdq36018jt        28c57a2b-df5a-54ff-8751-e3c60690face_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:2668->2668/tcp
kf4tl18zw13d        51fae34f-84dd-5e03-8af6-a53b54f391aa_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:2667->2667/tcp
kn8vhflaiskf        226aa4e4-d137-5a81-a219-18b0fa59a251_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:1767->1767/tcp
qwr806m38zhp        303a1493-95c3-52a1-a1d2-fc651061ac99_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:1100->1100/tcp
uzfk75nd9u3x        397a41bc-6808-5b1e-98f7-678a96d08ac8_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:1126->1126/tcp
v7rtwa3l8gps        445c6c61-c6d1-5cef-b771-10a05acc3859_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:2673->2673/tcp
n5ozcs2s0m7c        540b6a8e-caf8-504e-85c7-4910f99ff600_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:1377->1377/tcp
e0yct41zns2d        583fa47c-f9c5-5a60-8762-45febb496715_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:2671->2671/tcp
oc1n5km2g84k        599df1ec-b4d6-5530-8e80-4a339f67880c_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:2047->2047/tcp
4ytpoml76vmn        599f7c82-c90e-5358-9b92-59783189e29b_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:1301->1301/tcp
ag3xdbqdcprn        919de8c3-b940-558b-9984-d3960cdd34cf_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:2672->2672/tcp
o7srh5bhg0td        136030ab-f5db-5a9e-a2a3-d2c1cb1a33e4_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:2669->2669/tcp
9pihenwgnhi9        943215b0-7977-5855-9450-814b8b439ed9_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:1511->1511/tcp
ue3esbqlxkf2        b02deb9f-d85d-52ca-848d-4280612e8a0d_secondary   replicated          0/0                 atsigncompany/secondary:dev_env        *:2666->2666/tcp
```

2. Then choose one and start it up

 ``` docker service scale 445c6c61-c6d1-5cef-b771-10a05acc3859_secondary=1```

3. Then watch the log file

``` docker service logs -f 445c6c61-c6d1-5cef-b771-10a05acc3859_secondary```

example logs
```445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | INFO|2021-06-16 01:05:26.812248|AtSecondaryServer|currentAtSign : @superbyellowgreen
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    |
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | SEVERE|2021-06-16 01:05:26.881653|main|Exception in starting secondary server: FileSystemException: Creation failed, path = 'storage/commitLog' (OS Error: Transport endpoint is not connected, errno = 107)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    |
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | Unhandled exception:
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | FileSystemException: Creation failed, path = 'storage/commitLog' (OS Error: Transport endpoint is not connected, errno = 107)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | #0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:117)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | <asynchronous suspension>
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | #1      BackendManager.open (package:hive/src/backend/vm/backend_manager.dart:21)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | <asynchronous suspension>
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | #2      HiveImpl._openBox (package:hive/src/hive_impl.dart:106)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | <asynchronous suspension>
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | #3      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | <asynchronous suspension>
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | #4      CommitLogKeyStore.init (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:31)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | <asynchronous suspension>
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | #5      AtCommitLogManagerImpl.getCommitLog (package:at_persistence_secondary_server/src/log/commitlog/at_commit_log_manager_impl.dart:26)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | <asynchronous suspension>
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | #6      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:350)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | <asynchronous suspension>
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | #7      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:133)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | <asynchronous suspension>
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | #8      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | <asynchronous suspension>
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | #9      main (file:///app/at_secondary_server/bin/main.dart:21)
445c6c61-c6d1-5cef-b771-10a05acc3859_secondary.1.gc2mu2cha0q9@buzz-03    | <asynchronous suspension>
```

But all the mount points look fine as does gluster ???

**Expected behavior**
The secondary should start up cleanly

**Additional context**
Additional load was on the machine as these start and restart as NTP was tracking the docker interfaces and then hitting the resolver library. I have tuned ntp just to bind/watch the main machine ethernet interface

**Comment by cpswan** [comment]
`Transport endpoint is not connected` seems to be a characteristic error message for glusterfs

[GlusterFS transport endpoint is not connected – Quick fix!](https://bobcares.com/blog/glusterfs-transport-endpoint-is-not-connected/) concludes:

> In short, the error glusterfs transport endpoint connection fails mainly due to port unavailability or firewall problems.

**Comment by cpswan** [comment]
This is the sort of thing I'm seeing in `buzz-03:/var/log/glusterfs/bricks/gfs-brick.log`:

```
The message "I [MSGID: 139001] [posix-acl.c:252:posix_acl_log_permit_denied] 0-gfs-access-control: client: CTX_ID:68ed0b96-dd76-4789-89a9-bdb05dbc6555-GRAPH_ID:0-PID:3245-HOST:buzz-02-PC_NAME:gfs-client-2-RECON_NO:-0, gfid: 6af565c9-e6d7-458e-b202-460b65caf6ca, req(uid:1024,gid:1024,perm:3,ngrps:0), ctx(uid:0,gid:0,in-groups:0,perm:755,updated-fop:LOOKUP, acl:-) [Permission denied]" repeated 2 times between [2021-06-16 14:01:27.423556] and [2021-06-16 14:01:57.531515]
[2021-06-16 14:01:57.531532] E [MSGID: 115056] [server-rpc-fops_v2.c:507:server4_mkdir_cbk] 0-gfs-server: 25388666: MKDIR /@/secondaries/01/1c/cf/26/011ccf2653e6db38111446cd8295f80d/28c57a2b-df5a-54ff-8751-e3c60690face/storage.old/commitLog (6af565c9-e6d7-458e-b202-460b65caf6ca/commitLog) client: CTX_ID:68ed0b96-dd76-4789-89a9-bdb05dbc6555-GRAPH_ID:0-PID:3245-HOST:buzz-02-PC_NAME:gfs-client-2-RECON_NO:-0, error-xlator: gfs-access-control [Permission denied]
[2021-06-16 14:02:04.927044] I [MSGID: 139001] [posix-acl.c:252:posix_acl_log_permit_denied] 0-gfs-access-control: client: CTX_ID:68ed0b96-dd76-4789-89a9-bdb05dbc6555-GRAPH_ID:0-PID:3245-HOST:buzz-02-PC_NAME:gfs-client-2-RECON_NO:-0, gfid: 6af565c9-e6d7-458e-b202-460b65caf6ca, req(uid:1024,gid:1024,perm:3,ngrps:0), ctx(uid:0,gid:0,in-groups:0,perm:755,updated-fop:LOOKUP, acl:-) [Permission denied]
[2021-06-16 14:02:04.927194] E [MSGID: 115056] [server-rpc-fops_v2.c:507:server4_mkdir_cbk] 0-gfs-server: 25393422: MKDIR /@/secondaries/01/1c/cf/26/011ccf2653e6db38111446cd8295f80d/28c57a2b-df5a-54ff-8751-e3c60690face/storage.old/commitLog (6af565c9-e6d7-458e-b202-460b65caf6ca/commitLog) client: CTX_ID:68ed0b96-dd76-4789-89a9-bdb05dbc6555-GRAPH_ID:0-PID:3245-HOST:buzz-02-PC_NAME:gfs-client-2-RECON_NO:-0, error-xlator: gfs-access-control [Permission denied]
```

Why `[Permission denied]`?

Meanwhile in syslog:

```
Jun 16 14:04:28 buzz-03 kernel: [378402.380017] docker_gwbridge: port 452(veth2aefcbc) entered disabled state
Jun 16 14:04:28 buzz-03 systemd-networkd[675]: veth2aefcbc: Lost carrier
Jun 16 14:04:28 buzz-03 kernel: [378402.380703] veth68f024e: renamed from eth2
Jun 16 14:04:28 buzz-03 networkd-dispatcher[833]: ERROR:Unknown interface index 678826 seen even after reload
Jun 16 14:04:28 buzz-03 networkd-dispatcher[833]: WARNING:Unknown index 678822 seen, reloading interface list
Jun 16 14:04:28 buzz-03 systemd-udevd[1671286]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jun 16 14:04:28 buzz-03 systemd-networkd[675]: veth2aefcbc: Link DOWN
Jun 16 14:04:28 buzz-03 kernel: [378402.439200] docker_gwbridge: port 452(veth2aefcbc) entered disabled state
Jun 16 14:04:28 buzz-03 kernel: [378402.444198] device veth2aefcbc left promiscuous mode
Jun 16 14:04:28 buzz-03 kernel: [378402.444203] docker_gwbridge: port 452(veth2aefcbc) entered disabled state
Jun 16 14:04:28 buzz-03 systemd-networkd[675]: rtnl: received neighbor for link '678825' we don't know about, ignoring.
Jun 16 14:04:28 buzz-03 kernel: [378402.500693] br0: port 453(veth113134) entered disabled state
Jun 16 14:04:28 buzz-03 kernel: [378402.502776] device veth113134 left promiscuous mode
Jun 16 14:04:28 buzz-03 kernel: [378402.502781] br0: port 453(veth113134) entered disabled state
Jun 16 14:04:28 buzz-03 systemd-networkd[675]: rtnl: received neighbor for link '678825' we don't know about, ignoring.
Jun 16 14:04:28 buzz-03 systemd[1731]: run-docker-netns-0a7d8cdc087f.mount: Succeeded.
Jun 16 14:04:28 buzz-03 systemd[1731]: var-lib-docker-overlay2-5d5cea1a76130c9333485dabed76f51701ac3a32796f0a12cbff5e76bb79febc-merged.mount: Succeeded.
Jun 16 14:04:28 buzz-03 systemd[1]: run-docker-netns-0a7d8cdc087f.mount: Succeeded.
Jun 16 14:04:28 buzz-03 systemd[1]: var-lib-docker-overlay2-5d5cea1a76130c9333485dabed76f51701ac3a32796f0a12cbff5e76bb79febc-merged.mount: Succeeded.
Jun 16 14:04:28 buzz-03 networkd-dispatcher[833]: WARNING:Unknown index 678824 seen, reloading interface list
Jun 16 14:04:28 buzz-03 systemd[1149462]: run-docker-netns-0a7d8cdc087f.mount: Succeeded.
Jun 16 14:04:28 buzz-03 systemd[1149462]: var-lib-docker-overlay2-5d5cea1a76130c9333485dabed76f51701ac3a32796f0a12cbff5e76bb79febc-merged.mount: Succeeded.
Jun 16 14:04:28 buzz-03 dockerd[2060]: time="2021-06-16T14:04:28.929204051Z" level=error msg="fatal task error" error="task: non-zero exit (255)" module=node/agent/taskmanager node.id=jy6p28joumkcdgvtshacoqxj7 service.id=uyfdq36018jt50zz16t26l75i task.id=p80dnvgsnlxyg446r374e0036
Jun 16 14:04:28 buzz-03 networkd-dispatcher[833]: ERROR:Unknown interface index 678824 seen even after reload
Jun 16 14:04:28 buzz-03 networkd-dispatcher[833]: WARNING:Unknown index 678824 seen, reloading interface list
Jun 16 14:04:29 buzz-03 networkd-dispatcher[833]: ERROR:Unknown interface index 678824 seen even after reload
```

**Comment by cconstab** [comment]
The syslog logs are expected as each docker container joins the network interfaces.. We see the same logs on prod..

**Comment by cconstab** [comment]
Lots of testing today an spotting that the final secondaries that will not start all seem to have inconsitances in the glusterfs

Glusterfs thinks there is nothing wrong, but the files show up differently on buzz-03 as against buzz-01/02

rebooted  02/3 and glusterfs failed to load on 03 on reboot so all secondaries deployed to buzz-02. 900+ on buzz-02 which is pretty impressive, but even with just buzz-02 up the troublesome secondaries would not start.


**fix/workaround for faulty secondaries**
stop secondary 
```docker service scale 28c57a2b-df5a-54ff-8751-e3c60690face_secondary=0```

copy faulty secondary files over to tmp 

```root@buzz-02:~# cp -rp /gluster/@/secondaries/01/1c/cf/26/011ccf2653e6db38111446cd8295f80d/28c57a2b-df5a-54ff-8751-e3c60690face /tmp/sec```

mv the old directory (trying to delete it will likely fail)
```mv /gluster/@/secondaries/01/1c/cf/26/011ccf2653e6db38111446cd8295f80d/28c57a2b-df5a-54ff-8751-e3c60690face  /gluster/@/secondaries/01/1c/cf/26/011ccf2653e6db38111446cd8295f80d/28c57a2b-df5a-54ff-8751-e3c60690face.broken```

then copy back the files from tmp
```cp -rp /tmp/sec/* /gluster/@/secondaries/01/1c/cf/26/011ccf2653e6db38111446cd8295f80d/```

refresh the certificates as those files handles also see broken 
```/usr/local/bin/certbot-zerossl renew --force-renewal --deploy-hook /gluster/@/api/renewal-hooks.sh --cert-name 28c57a2b-df5a-54ff-8751-e3c60690face.buzz.do-sf2.atsign.zone```

finally restart the secondary
```docker service scale 28c57a2b-df5a-54ff-8751-e3c60690face_secondary=1```

check with openssl
```root@buzz-03:~# openssl s_client -quiet 0:2668
Can't use SSL_get_servername
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = AT, O = ZeroSSL, CN = ZeroSSL RSA Domain Secure Site CA
verify return:1
depth=0 CN = 28c57a2b-df5a-54ff-8751-e3c60690face.buzz.do-sf2.atsign.zone
verify return:1
@scan
data:["signing_publickey@macaroniunemployed"]
@
```

finally check the logs

``` docker service logs --tail 20 -f 28c57a2b-df5a-54ff-8751-e3c60690face_secondary```

Only really odd thing is gluster should not fail this way and the logs files are not matching the secondary unless the -f option is given (now thats odd!)

**Comment by cconstab** [comment]
replicating glusterFS setup @home to make sure removing and adding brick solves this issue..

**Comment by cconstab** [comment]
I went through the process above for all the secondaires that were still failing and they all came back up however with one addition I had to also remove all the lock files once the storage files were copied back.. That resulted in every secondary recovering..

At this point all servers reporting the same bytes used

```
root@buzz-03:~#  df -k /gluster
Filesystem     1K-blocks    Used Available Use% Mounted on
localhost:/gfs 104806400 3126576 101679824   3% /gluster
root@buzz-03:~#
```
```
root@buzz-02:~#  df -k /gluster
Filesystem     1K-blocks    Used Available Use% Mounted on
localhost:/gfs 104806400 3126576 101679824   3% /gluster
root@buzz-02:~#
```
```
root@buzz-01:~#  df -k /gluster
Filesystem     1K-blocks    Used Available Use% Mounted on
localhost:/gfs 104806400 3126576 101679824   3% /gluster
root@buzz-01:~#
```

and all secondaries are up.. 

```
root@buzz-01:~# docker service ls |grep 0/0
root@buzz-01:~# docker service ls |grep 0/0|wc -l
0
root@buzz-01:~# docker service ls |grep 1/1|wc -l
919
root@buzz-01:~# docker service ls |grep 0/1|wc -l
0
root@buzz-01:~#
```

Only outstanding question is do the devs want the certs renewed ?? Due to the ZeroSSL issues this week ? This does not effect android so my suggestion is if you are an Apple dev and hit a problem we will update your certs on demand..

Feedback please

@sarika01 
@murali-shris 
@purnimavenkatasubbu 
@Sameeraja-Bharathula 
@cpswan 
@nickelskevin

**Comment by nickelskevin** [comment]
That seems like a reasonable plan to me.

**Comment by cpswan** [comment]
Given that we already have the scripts, it might be easier to just run them rather than responding to onesies and twosies.

I'll have a quick look to see how bad things are.

**Comment by cpswan** [comment]
```
./checkcerts.sh
unable to load certificate
140458169120064:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
unable to load certificate
140702707995968:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
Invalid certs from April 0
Invalid certs from May 
```

**Comment by cconstab** [comment]
Alright thanks for everyone's help I think we can close this issue... But I will leave open for a few days just in case someone has anything to add..

**Comment by cpswan** [comment]
Closing, as it's been more than a few days, and we've not seen further issues.
