### ISSUE TITLE
Exception in secondary when using @mosphere  version 1.0.7(50)

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#299]

**Comment by cconstab** [comment]
@mosphere errors when sending files (plus all my contacts are gone in app) but this is the exception seen in the secondary..


```

79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | FINER|2021-08-26 19:25:26.187417|SyncVerbHandler|regex for sync : (.mosphere|atconnections|[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12})
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #0      SyncVerbHandler.processVerb.<anonymous closure> (package:at_secondary/src/verb/handler/sync_verb_handler.dart:51)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #1      Sort._insertionSort (dart:_internal/sort.dart:69)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #2      Sort._doSort (dart:_internal/sort.dart:58)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #3      Sort.sort (dart:_internal/sort.dart:33)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #4      ListMixin.sort (dart:collection/list.dart:356)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #5      SyncVerbHandler.processVerb (package:at_secondary/src/verb/handler/sync_verb_handler.dart:50)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #6      AbstractVerbHandler.processInternal (package:at_secondary/src/verb/handler/abstract_verb_handler.dart:48)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #7      AbstractVerbHandler.process (package:at_secondary/src/verb/handler/abstract_verb_handler.dart:32)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #8      DefaultVerbExecutor.execute (package:at_secondary/src/verb/executor/default_verb_executor.dart:27)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #9      AtSecondaryServerImpl._executeVerbCallBack (package:at_secondary/src/server/at_secondary_impl.dart:301)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | #10     InboundMessageListener._messageHandler (package:at_secondary/src/connection/inbound/inbound_message_listener.dart:73)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.g1timnfv47ks@hornet-04    | <asynchronous suspension>

```

**Comment by cconstab** [comment]
Set as P1 as at present the @mospher app does not work.. After multiple tests only one file got transferred.. Equally this may also be an app issue.. Tough to tell when testing, but the secondary should not err.

@sarika01 we probably need testing of the app using prod secondaries by the developer before we test the app in our twice a week testing meetings...

@tinashe404  please add  any thoughts.. thanks

**Comment by murali-shris** [comment]
Duplicate of https://github.com/atsign-foundation/apps/issues/228

**Comment by gkc** [comment]
Triaged in an old-issue sweep. The crash site — `SyncVerbHandler.processVerb` sorting the full in-memory commit-change list before stripping null commitIds — no longer exists: `SyncVerbHandler`/`SyncFromVerbHandler` were deleted in commit 709bc0c3 during the Progressive Sync rewrite. The current `SyncProgressiveVerbHandler` streams via `commitLog.iterate(...)` and defensively guards null commitIds/atKeys, so this exception cannot recur on trunk. Closing as completed.
