### ISSUE TITLE
No such method error while starting the servers in the local environment

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#334]
**Describe the bug**
While starting the servers with the latest branch of trunk locally. The server exits with the no such method error.

**To Reproduce**
1. First Pull the latest branch of server 
2. Then Change the storage, Domain and certs in the config file
3. And then start the server

**Expected behavior**
Server should start without any error messages.

**Server logs**
Unhandled exception:
NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add("private:_00bc2460-4195-4f7c-bb4b-044d0d92355d@sitaram")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      HiveKeystore.getExpiredKeys.<anonymous closure> (package:at_persistence_secondary_server/src/keystore/hive_keystore.dart:226:21)
<asynchronous suspension>

**Comment by purnimavenkatasubbu** [comment]
Re-tested this issue with the latest bug fixes. The server starts without any issues.

![Screenshot from 2021-10-13 15-51-43](https://user-images.githubusercontent.com/43639593/137115314-c9307ed1-0f9a-4cba-86c3-f6f6ea54321a.png)
