### ISSUE TITLE
Sync issues with the staging atsigns while using wavi and buzz app

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#339]
**Describe the bug**
With the staging atsigns, Whenever I add data it is not being synced. instead, I see some exceptions in the logs

**To Reproduce**
1. First I Installed the buzz app and authenticated with the staging atsign.
2. Then I added some data and saved it.
3. And Checked the app logs

**Expected behavior**
All the data should be saved

**App Logs **

**Atsign-1 ( purnima💙)**
I/flutter (16738): #7      SyncServiceImpl._getServerCommitId
package:at_client/…/service/sync_service_impl.dart:405
I/flutter (16738): <asynchronous suspension>
I/flutter (16738): #6      SyncUtil.getLatestServerCommitId
package:at_client/…/util/sync_util.dart:85
I/flutter (16738): #5      jsonDecode (dart:convert/json.dart:96:10)
I/flutter (16738): #4      JsonCodec.decode (dart:convert/json.dart:157:41)
I/flutter (16738): #3      JsonDecoder.convert (dart:convert/json.dart:506:36)
I/flutter (16738): #2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
I/flutter (16738): #1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:522:7)
I/flutter (16738): FINEST|2021-10-13 12:16:16.137437|SyncService|#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
I/flutter (16738): FINER|2021-10-13 12:16:12.689608|SyncService|got stats notification in sync: 1335
I/ViewRootImpl@a9adb44[MainActivity](16738): stopped(true) old=false
I/SurfaceView(16738): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{e4eed62 V.E...... ........ 0,0-1080,2340} of ViewRootImpl@a9adb44[MainActivity]

FINER|2021-10-13 12:29:39.099629|SyncUtil|localCommitId:null
I/flutter (16738): FINER|2021-10-13 12:29:39.102584|SyncUtil|serverCommitId:521
I/flutter (16738): FINER|2021-10-13 12:29:39.105200|SyncUtil|changed entries: 3
I/flutter (16738): INFO|2021-10-13 12:29:39.406655|SyncService|Returning the serverCommitId 521
I/flutter (16738): FINER|2021-10-13 12:29:39.409526|SyncService|Sync in progress
I/flutter (16738): FINER|2021-10-13 12:29:39.414565|SyncService|syncing to local
I/flutter (16738): FINER|2021-10-13 12:29:39.417053|SyncService|** syncBuilder sync:from:-1:limit:100

I/flutter (16738):  true
I/flutter (16738): FINER|2021-10-13 12:30:22.139570|SyncService|clearing sync queue
I/flutter (16738): SyncDoneEvent Connections
I/flutter (16738): Current @sign:::::@ purnima💙
I/flutter (16738): SyncDoneEvent Connections
I/flutter (16738): _onSuccessCallback 2021-10-13 12:30:22.133449Sync status: SyncStatus.failure lastSyncedOn: 2021-10-13 07:00:22.132721Z Exception: AT0025: FormatException: Unexpected end of input (at character 1)
I/flutter (16738): FINER|2021-10-13 12:30:20.635101|SyncService|got stats notification in sync: 521
I/flutter (16738): FINER|2021-10-13 12:30:02.426077|Monitor|monitor started for @ purnima💙 with last notification time: null
I/flutter (16738): 

**Atsign- 2 (1indianmusicpoor)**

I/flutter (16738): FINER|2021-10-13 12:13:06.042203|SyncService|got stats notification in sync: 1335
I/ViewRootImpl@a9adb44[MainActivity](16738): ViewPostIme pointer 1
I/ViewRootImpl@a9adb44[MainActivity](16738): ViewPostIme pointer 0
I/flutter (16738): FINER|2021-10-13 12:12:46.254353|SyncService|got stats notification in sync: 1335
FINER|2021-10-13 12:13:06.042203|SyncService|got stats notification in sync: 1335
I/flutter (16738): _onSuccessCallback 2021-10-13 12:13:13.692832Sync status: SyncStatus.failure lastSyncedOn: 2021-10-13 06:43:13.681145Z Exception: AT0025: FormatException: Unexpected end of input (at character 1)
I/flutter (16738):
I/flutter (16738): ^
I/flutter (16738):  true
I/flutter (16738): FINER|2021-10-13 12:12:34.431008|SyncService|** syncBuilder sync:from:-1:limit:100
I/flutter (16738): FINER|2021-10-13 12:12:34.429715|SyncService|syncing to local
I/flutter (16738): FINER|2021-10-13 12:12:34.425908|SyncService|Sync in progress
I/flutter (16738): INFO|2021-10-13 12:12:34.424657|SyncService|Returning the serverCommitId 1335
I/flutter (16738): FINER|2021-10-13 12:12:34.110080|SyncUtil|changed entries: 1
I/flutter (16738): FINER|2021-10-13 12:12:34.108931|SyncUtil|serverCommitId:1335
I/flutter (16738):  true
I/flutter (16738): FINER|2021-10-13 12:13:13.724778|SyncService|clearing sync queue
I/flutter (16738): SyncDoneEvent Connections
I/flutter (16738): Current @sign:::::@ 1indianmusicpoor
I/flutter (16738): SyncDoneEvent Connections
I/flutter (16738): Current @sign:::::@ 1indianmusicpoor

**Screenshots**
![Screenshot from 2021-10-13 12-36-17](https://user-images.githubusercontent.com/43639593/137083919-2a75d865-3221-497c-923c-28dd0e61d1d7.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14.1]
 - Version [e.g. 59]

**Were you using an @‎application when the bug was found?**
  - [e.g. @‎ buzz and @ wavi]

**Additional context**

**Comment by murali-shris** [comment]
@purnimavenkatasubbu please retest this issue

**Comment by purnimavenkatasubbu** [comment]
Retested the issue with the above-mentioned staging atsigns. Adding logs below.

**Atsign 1 : purnima💙 with buzz**

: FINER|2021-12-01 14:43:25.450016|SyncUtil|localCommitId:null
I/flutter (17967): FINER|2021-12-01 14:43:25.451353|SyncUtil|serverCommitId:579
I/flutter (17967): FINER|2021-12-01 14:43:25.452609|SyncUtil|changed entries: 1
I/flutter (17967): INFO|2021-12-01 14:43:25.740264|SyncService|Returning the serverCommitId 579
I/flutter (17967): FINER|2021-12-01 14:43:25.743592|SyncService|Sync in progress
I/flutter (17967): FINER|2021-12-01 14:43:25.754325|CommitLogKeyStore|startKey: 0 all commit log entries: [CommitEntry{AtKey: public:publickey@ purnima💙, operation: CommitOp.UPDATE, commitId:null, opTime: 2021-12-01 09:12:58.249088Z, internal_seq: 0}]
I/flutter (17967): FINER|2021-12-01 14:43:25.762112|SyncService|syncing to local
I/flutter (17967): FINER|2021-12-01 14:43:25.763784|SyncService|** syncBuilder sync:from:-1:limit:100:.buzz
I/flutter (17967):
I/flutter (17967): _onSuccessCallback 2021-12-01 14:43:26.923241Sync status: SyncStatus.failure lastSyncedOn: 2021-12-01 09:13:26.920333Z Exception: AT0025: ErrorCode: AT0015 - Exception: key not found : cached:@ purnima💙:company**information.buzz@violetred7ready does not exist in keystore true
I/flutter (17967): FINER|2021-12-01 14:43:26.934870|SyncService|clearing sync queue

**Atsign1 : purnima💙 with wavi**

FINER|2021-12-01 15:00:45.616741|SyncService|syncing to local
I/flutter (11050): FINER|2021-12-01 15:00:45.617478|SyncService|** syncBuilder sync:from:579:limit:10:.(wavi|persona)@
I/flutter (11050):
I/flutter (11050): _onSuccessCallback 2021-12-01 15:00:45.916616Sync status: SyncStatus.success lastSyncedOn: 2021-12-01 09:30:45.916437Z Exception: null true


**Atsign2 : 1indianmusicpoor with both buzz and wavi**

 FINER|2021-12-01 14:44:55.761024|AtLookup|AtLookup.findSecondary got answer: a33e5004-4a1e-59af-9325-44f7b250772a.buzz.do-sf2.atsign.zone:2983 and closing connection
I/flutter (17967): FINER|2021-12-01 14:44:55.762335|AtLookup|AtLookup.findSecondary received atsign: @1indianmusicpoor
I/flutter (17967): FINER|2021-12-01 14:44:57.137999|AtLookup|AtLookup.findSecondary got answer: a33e5004-4a1e-59af-9325-44f7b250772a.buzz.do-sf2.atsign.zone:2983 and closing connection
I/flutter (17967): SEVERE|2021-12-01 14:44:58.091012|AtLookup|Exception in sending to server, HandshakeException: Handshake error in client (OS Error:
I/flutter (17967): 	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:359))
I/flutter (17967): SEVERE|2021-12-01 14:44:58.092523|AtLookup|Error in remote verb execution HandshakeException: Handshake error in client (OS Error:
I/flutter (17967): 	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:359))
I/flutter (17967): _getServerStatus error: ErrorCode: AT0014 - Exception: Unknown AtClient exception

![image](https://user-images.githubusercontent.com/43639593/144206701-d97ede33-1260-4bf9-afed-469b706e037c.png)
