### ISSUE TITLE
Hive errors with staging secondary @forestgreenquerulous1

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#341]
**Describe the bug**

Secondary won't start up.

From the container logs:

```
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | FINER|2021-10-15 09:16:38.147750|HivePersistenceManager|getHiveSecretFromFile fetching hiveSecretString for @forestgreenquerulous1 from file
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | FINER|2021-10-15 09:16:38.147786|HivePersistenceManager|getHiveSecretFromFile found filePath: storage/hive/7ea75eeca5eb4d8e5e23ca54117a13db8afb7e8bf7b0878e1667305b4c3c81e0.hash
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | AtServer.getHiveSecretFromFile file found
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | FINER|2021-10-15 09:16:38.151048|HivePersistenceManager|AtPersistence.openVault received atsign: @forestgreenquerulous1
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | SEVERE|2021-10-15 09:16:38.175840|HivePersistenceManager|AtPersistence().openVault error: HiveError: This should not happen. Please open an issue on GitHub.
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | FINEST|2021-10-15 09:16:38.175986|HivePersistenceManager|scheduleKeyExpireTask starting cron job.
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | Unhandled exception:
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | HiveError: This should not happen. Please open an issue on GitHub.
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | INFO|2021-10-15 09:16:20.947652|AtSecondaryServer|currentAtSign : @forestgreenquerulous1
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | FINER|2021-10-15 09:16:20.961435|CommitLogKeyStore|last committed sequence: 639
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | INFO|2021-10-15 09:16:20.961470|CommitLogKeyStore|Keystore initialized successfully
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | INFO|2021-10-15 09:16:20.973208|AccessLogKeyStore|Keystore initialized successfully
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | FINER|2021-10-15 09:16:20.984539|HivePersistenceManager|AtPersistence.init received storagePath: storage/hive
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | FINER|2021-10-15 09:16:20.984573|HivePersistenceManager|getHiveSecretFromFile fetching hiveSecretString for @forestgreenquerulous1 from file
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | FINER|2021-10-15 09:16:20.984599|HivePersistenceManager|getHiveSecretFromFile found filePath: storage/hive/7ea75eeca5eb4d8e5e23ca54117a13db8afb7e8bf7b0878e1667305b4c3c81e0.hash
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | AtServer.getHiveSecretFromFile file found
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | FINER|2021-10-15 09:16:20.987607|HivePersistenceManager|AtPersistence.openVault received atsign: @forestgreenquerulous1
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | SEVERE|2021-10-15 09:16:21.047667|HivePersistenceManager|AtPersistence().openVault error: HiveError: This should not happen. Please open an issue on GitHub.
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | FINEST|2021-10-15 09:16:21.047743|HivePersistenceManager|scheduleKeyExpireTask starting cron job.
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    |
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #6      HivePersistenceManager.openVault (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:68)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | Unhandled exception:
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | HiveError: This should not happen. Please open an issue on GitHub.
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #7      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:385)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #8      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #9      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | #10     main (file:///app/at_secondary_server/bin/main.dart:21)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #6      HivePersistenceManager.openVault (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:68)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.pzt7kqyzs5qe@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #7      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:385)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #8      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #9      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | <asynchronous suspension>
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | #10     main (file:///app/at_secondary_server/bin/main.dart:21)
c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary.1.iejggujn2azl@buzz-02    | <asynchronous suspension>
```

**To Reproduce**
1. Log on to buzz-01
2. `sudo docker service scale c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary=1`
3. `sudo docker service logs c0deb0f2-308e-5915-8551-0cc9e94e9c3b_secondary`

**Expected behavior**
Secondary starts and becomes reachable with openssl

**Comment by murali-shris** [comment]
@cpswan should we recover hive box for this atsign?

**Comment by cpswan** [comment]
@murali-shris yes, I just sent it to you.

**Comment by cpswan** [comment]
@murali-shris ran this through his repair tool and it's now back online
