### ISSUE TITLE
NULL err on New Secondary causing secondary to crash hard

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#348]
**Describe the bug**
I think my secondary for @ colin has been update to I ran @ buzz. Everthing was repporting fine until I ran @ buzz.. Then I could not log in..
Look at logs and saw message below..

**To Reproduce**
1. Wait for new secondary build 
2. Then I ran @ buzz
3. And then checked logs

**Expected behavior**
@ buzz to work and the secondary not to fail... @ colin secondary now constantly rebooting with NULL error

**Screenshots**

See comment

**Concern**
That I am not unlucky and this will happen to other @ signs

**Comment by cconstab** [comment]
```
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | Unhandled exception:
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | type 'Null' is not a subtype of type 'int'
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | #0      CommitLogKeyStore._getCommitIdMap.<anonymous closure> (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:290)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | #1      _GrowableList.forEach (dart:core-patch/growable_array.dart:403)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | #2      CommitLogKeyStore._getCommitIdMap (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:286)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | #3      CommitLogKeyStore.init (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:44)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | #4      AtCommitLogManagerImpl.getCommitLog (package:at_persistence_secondary_server/src/log/commitlog/at_commit_log_manager_impl.dart:26)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | #5      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:359)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | #6      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | #7      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | #8      main (file:///app/at_secondary_server/bin/main.dart:21)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.idak96xvxw77@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | INFO|2021-10-19 02:25:10.768510|AtSecondaryServer|currentAtSign : @colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | FINER|2021-10-19 02:25:10.871704|CommitLogKeyStore|last committed sequence: 9919
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | INFO|2021-10-19 02:25:10.871811|CommitLogKeyStore|Keystore initialized successfully
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | Unhandled exception:
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | type 'Null' is not a subtype of type 'int'
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | #0      CommitLogKeyStore._getCommitIdMap.<anonymous closure> (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:290)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | #1      _GrowableList.forEach (dart:core-patch/growable_array.dart:403)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | #2      CommitLogKeyStore._getCommitIdMap (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:286)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | #3      CommitLogKeyStore.init (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:44)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | #4      AtCommitLogManagerImpl.getCommitLog (package:at_persistence_secondary_server/src/log/commitlog/at_commit_log_manager_impl.dart:26)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | #5      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:359)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | #6      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | #7      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | #8      main (file:///app/at_secondary_server/bin/main.dart:21)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.7kuorc4f23ba@hornet-07    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | INFO|2021-10-19 02:25:23.400286|AtSecondaryServer|currentAtSign : @colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | FINER|2021-10-19 02:25:23.553607|CommitLogKeyStore|last committed sequence: 9919
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | INFO|2021-10-19 02:25:23.553736|CommitLogKeyStore|Keystore initialized successfully
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | Unhandled exception:
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | type 'Null' is not a subtype of type 'int'
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | #0      CommitLogKeyStore._getCommitIdMap.<anonymous closure> (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:290)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | #1      _GrowableList.forEach (dart:core-patch/growable_array.dart:403)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | #2      CommitLogKeyStore._getCommitIdMap (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:286)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | #3      CommitLogKeyStore.init (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:44)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | #4      AtCommitLogManagerImpl.getCommitLog (package:at_persistence_secondary_server/src/log/commitlog/at_commit_log_manager_impl.dart:26)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | #5      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:359)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | #6      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | #7      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | #8      main (file:///app/at_secondary_server/bin/main.dart:21)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.zds1fii7dmvr@hornet-08    | <asynchronous suspension>
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.o0m576854dzc@hornet-06    | INFO|2021-10-19 02:25:35.566925|AtSecondaryServer|currentAtSign : @colin

```

**Comment by buzz** [comment]
> @ buzz

Please don't mention my username. Thank you

**Comment by sitaram-kalluri** [comment]
Added defensive fix to resolve server crash on null value and moved the code to production. That being said, the CommitId should not be null. Added logs for further debugging.

**Comment by cconstab** [comment]
The original "Null" is fixed as the server stays up now but now seeing these Nulls in the logs..

```
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:33:43.745600|PkamVerbHandler|Verb : pkam  Response: Response{_data: success, _type: null, _isError: false, _errorMessage: null}
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:33:43.890557|InboundListener|command received: stats:3 sessionID:_e66c9250-719b-463c-a53e-e0825e68324a
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:33:43.890603|AtSecondaryServer|inside _executeVerbCallBack: stats:3
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:33:43.891887|DefaultVerbExecutor|verb handler found : StatsVerbHandler
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:33:43.895131|StatsVerbHandler|In statsVerbHandler statID : :3, regex : null
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:33:43.896902|StatsVerbHandler|addStatToResult for id : 3, regex: null
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:33:43.898525|RegexUtil|In commitID getMetrics...regex : null
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:33:44.032280|StatsVerbHandler|Verb : stats  Response: Response{_data: [{"id":"3","name":"lastCommitID","value":"9919"}], _type: null, _isError: false, _errorMessage: null}
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |


```

**Comment by sitaram-kalluri** [comment]
@cconstab: The "Null" in the above logs are expected. 

The "Null" beside the regex means the regular expression is not passed to filter the commit log entries while returning the last commit id.

The "Null" in Response bean is place holder that gets populated when an exception/error occurs.

**Comment by cconstab** [comment]
Thank you..

**Comment by sitaram-kalluri** [comment]
@cconstab: The issue is resolved. Can you please verify and close the issue?

**Comment by cconstab** [comment]
Looks good after fix thank you.. Not seeing the problem any more
