### ISSUE TITLE
Certificate Issues on Production in the logs (looks like Secondary to Secondary connections not Confirmed)

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#350]
**Describe the bug**
Seeing Certificate Errors in the Logs

**To Reproduce**
1.Just tail the logs on a @ sign
2. Run the @ buzz app and watch the logs

**Expected behavior**
No cert errors

**Screenshots**
Log files below

**Were you using an @‎application when the bug was found?**
  - @ buzz,

**Comment by cconstab** [comment]
```
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:39:39.297768|InboundConnectionImpl|InternetAddress('10.10.89.90', IPv4):59397 Disconnected
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:39:39.303654|InboundConnectionImpl|InternetAddress('10.10.89.90', IPv4):59389 Disconnected
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:39:39.312776|InboundConnectionImpl|InternetAddress('10.10.89.90', IPv4):59425 Disconnected
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:11.064679|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |    WRONG_VERSION_NUMBER(tls_record.cc:242))
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:14.409898|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |    HTTP_REQUEST(s3_both.cc:576))
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:17.202179|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |    WRONG_VERSION_NUMBER(tls_record.cc:242))
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:19.671574|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |    WRONG_VERSION_NUMBER(tls_record.cc:242))
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:22.326241|AtSecondaryServer|HandshakeException: Connection terminated during handshake
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:43:25.159474|AtSecondaryServer|In _listen - clientSocket.peerCertificate : null
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | FINER|2021-10-19 14:43:27.157398|InboundConnectionImpl|InternetAddress('10.10.89.90', IPv4):37094 Disconnected
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:30.627545|AtSecondaryServer|HandshakeException: Connection terminated during handshake
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:31.065212|AtSecondaryServer|HandshakeException: Connection terminated during handshake
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:40.675304|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |    NO_SHARED_CIPHER(handshake_server.cc:712))
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:41.998434|AtSecondaryServer|HandshakeException: Connection terminated during handshake
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:42.534007|AtSecondaryServer|HandshakeException: Connection terminated during handshake
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:43.201294|AtSecondaryServer|HandshakeException: Connection terminated during handshake
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:43.767189|AtSecondaryServer|HandshakeException: Connection terminated during handshake
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:44.521251|AtSecondaryServer|SocketException: OS Error: Connection reset by peer, errno = 104, address = 0.0.0.0, port = 1029
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:44.822459|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |    NO_SHARED_CIPHER(tls13_server.cc:218))
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:47.143068|AtSecondaryServer|HandshakeException: Connection terminated during handshake
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:44:03.513314|AtSecondaryServer|HandshakeException: Connection terminated during handshake

```

**Comment by cconstab** [comment]
More Errors


```
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.528451|SyncProgressiveVerbHandler|atData is null for @barbara:address**contact_details.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.531148|SyncProgressiveVerbHandler|atData is null for @barbara:chicks**work.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.534675|SyncProgressiveVerbHandler|atData is null for @barbara:email**work.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.535919|SyncProgressiveVerbHandler|atData is null for @barbara:file_shared_key@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.570566|SyncProgressiveVerbHandler|atData is null for @barbara:hello_friends**work.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.572033|SyncProgressiveVerbHandler|atData is null for @barbara:kiiten**kitten_pics.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.574533|SyncProgressiveVerbHandler|atData is null for @barbara:my_life_for_the_last_four_days**work.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.576159|SyncProgressiveVerbHandler|atData is null for @barbara:name**contact_details.buzz@colin

79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.577088|SyncProgressiveVerbHandler|atData is null for @barbara:name**work.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.580119|SyncProgressiveVerbHandler|atData is null for @barbara:phone**contact_details.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.583302|SyncProgressiveVerbHandler|atData is null for @barbara:phone**work.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.585215|SyncProgressiveVerbHandler|atData is null for @barbara:skipper**work.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.587009|SyncProgressiveVerbHandler|atData is null for @barbara:skipper_play**kitten_pics.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.588122|SyncProgressiveVerbHandler|atData is null for @barbara:skipper_yawn**kitten_pics.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.588941|SyncProgressiveVerbHandler|atData is null for @barbara:two_of_the_three_kittens**kitten_pics.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | INFO|2021-10-19 14:58:56.590534|SyncProgressiveVerbHandler|atData is null for @barbara:view_from_desk**contact_details.buzz@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    |




````

**Comment by cconstab** [comment]
Might have been me just being unlucky and catching the logs files at just the right time.. This is the severe issues over the last 12 hours..

```
cconstab@hornet-01:~$ docker service logs --timestamps  --since 12h 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary |grep SEVERE
2021-10-19T13:59:04.061459450Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | Unhandled exception:
2021-10-19T13:59:26.062615479Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 13:59:26.062312|CommitLogKeyStore|CommitID is null for image.persona@jantuma. Skipping to update entry into commitLogCacheMap
2021-10-19T13:59:04.061514650Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | type 'Null' is not a subtype of type 'int'
2021-10-19T13:59:26.062693954Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 13:59:26.062357|CommitLogKeyStore|CommitID is null for image.persona@jantuma. Skipping to update entry into commitLogCacheMap
2021-10-19T13:59:04.061522804Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | #0      CommitLogKeyStore._getCommitIdMap.<anonymous closure> (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:290)
2021-10-19T13:59:04.061534054Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | #1      _GrowableList.forEach (dart:core-patch/growable_array.dart:403)
2021-10-19T13:59:04.061540498Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | #2      CommitLogKeyStore._getCommitIdMap (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:286)
2021-10-19T13:59:04.061547002Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | <asynchronous suspension>
2021-10-19T13:59:04.061552895Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | #3      CommitLogKeyStore.init (package:at_persistence_secondary_server/src/log/commitlog/commit_log_keystore.dart:44)
2021-10-19T13:59:04.061558805Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | <asynchronous suspension>
2021-10-19T13:59:04.061564529Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | #4      AtCommitLogManagerImpl.getCommitLog (package:at_persistence_secondary_server/src/log/commitlog/at_commit_log_manager_impl.dart:26)
2021-10-19T13:59:04.061571243Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | <asynchronous suspension>
2021-10-19T13:59:04.061577709Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | #5      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:359)
2021-10-19T13:59:04.061584235Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | <asynchronous suspension>
2021-10-19T13:59:04.061589959Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | #6      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
2021-10-19T13:59:04.061595909Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | <asynchronous suspension>
2021-10-19T13:59:04.061601890Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | #7      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
2021-10-19T13:59:04.061607783Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | <asynchronous suspension>
2021-10-19T13:59:04.061613197Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | #8      main (file:///app/at_secondary_server/bin/main.dart:21)
2021-10-19T13:59:04.061618576Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.81w0z2ub7jw0@hornet-06    | <asynchronous suspension>
2021-10-19T14:33:32.573460675Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:33:32.572278|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:33:33.664617257Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:33:33.664021|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:33:35.735036770Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:33:35.734896|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:33:43.144939079Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:33:43.143086|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:37:36.219566190Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:37:36.219382|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:43:11.065864768Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:11.064679|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
2021-10-19T14:43:14.410112282Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:14.409898|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
2021-10-19T14:43:17.202352423Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:17.202179|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
2021-10-19T14:43:19.671740804Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:19.671574|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
2021-10-19T14:43:22.326423038Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:22.326241|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:43:30.627826100Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:30.627545|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:43:31.065400199Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:31.065212|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:43:40.675464395Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:40.675304|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
2021-10-19T14:43:41.998678506Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:41.998434|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:43:42.534174623Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:42.534007|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:43:43.201765488Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:43.201294|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:43:43.767567658Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:43.767189|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:43:44.521404775Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:44.521251|AtSecondaryServer|SocketException: OS Error: Connection reset by peer, errno = 104, address = 0.0.0.0, port = 1029
2021-10-19T14:43:44.822617881Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:44.822459|AtSecondaryServer|HandshakeException: Handshake error in server (OS Error:
2021-10-19T14:43:47.145563598Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:43:47.143068|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:44:03.513550083Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:44:03.513314|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:50:25.111978111Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:50:25.111409|AtSecondaryServer|HandshakeException: Connection terminated during handshake
2021-10-19T14:53:55.126336763Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:53:55.126139|DefaultResponseHandler|exception in writing response to socket:Instance of 'ConnectionInvalidException'
2021-10-19T14:57:42.863628365Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:57:42.863507|PolResponseHandler|exception in writing response to socket:Instance of 'ConnectionInvalidException'
2021-10-19T14:58:04.725701975Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 14:58:04.723806|DefaultResponseHandler|exception in writing response to socket:Instance of 'ConnectionInvalidException'
2021-10-19T15:00:43.412918102Z 79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.xcl6of5x8jg0@hornet-06    | SEVERE|2021-10-19 15:00:43.399830|AtSecondaryServer|HandshakeException: Connection terminated during handshake
error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node jlgazzjh7im1maj0afmd7488c is not available
```

**Comment by cpswan** [comment]
This reads like three different (classes of) error, the latter two being unrelated to certs. I'd suggest splitting into separate tickets so that we can keep track of them with some clarity rather than having potential confusion of trying to track down three different root causes.

The wrong version errors are different from what we saw last week with the expired DST X3 root (and also different to the issues @kalluriramkumar brought up earlier).

**Comment by cconstab** [comment]
> This reads like three different (classes of) error, the latter two being unrelated to certs. I'd suggest splitting into separate tickets so that we can keep track of them with some clarity rather than having potential confusion of trying to track down three different root causes.
> 
> The wrong version errors are different from what we saw last week with the expired DST X3 root (and also different to the issues @kalluriramkumar brought up earlier).

Agreed... 
I will open another ticket for the oddness in the logs files when using @ buzz

**Comment by cconstab** [comment]
Lets focus this thread on the certs... This could well be a dess server with old cacerts being presented..  I

**Comment by cpswan** [comment]
Every secondary should by now have the new cacerts with DST X3 cut out.

**Comment by cconstab** [comment]
Closing as fix in place and working well
