### ISSUE TITLE
Production secondary @highvibes failing to start due to Hive errors

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#369]
**Describe the bug**

Secondary fails to start, and is in a constant restart loop.

Here's a log snippet:

```
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | AtServer.getHiveSecretFromFile file found
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | FINER|2021-10-28 08:35:51.793030|HivePersistenceManager|AtPersistence.openVault received atsign: @highvibes
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    |
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | SEVERE|2021-10-28 08:35:53.942354|HivePersistenceManager|AtPersistence().openVault error: HiveError: This should not happen. Please open an issue on GitHub.
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    |
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | FINEST|2021-10-28 08:35:53.943688|HivePersistenceManager|scheduleKeyExpireTask starting cron job.
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    |
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | SEVERE|2021-10-28 08:35:53.958081|HiveKeystore|HiveKeystore get error: HiveError: Box not found. Did you forget to call Hive.openBox()?
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    |
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | Unhandled exception:
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | HiveError: This should not happen. Please open an issue on GitHub.
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | <asynchronous suspension>
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | <asynchronous suspension>
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | <asynchronous suspension>
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | <asynchronous suspension>
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #6      HivePersistenceManager.openVault (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:65)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | <asynchronous suspension>
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #7      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:385)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | <asynchronous suspension>
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #8      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | <asynchronous suspension>
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #9      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | <asynchronous suspension>
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | #10     main (file:///app/at_secondary_server/bin/main.dart:21)
f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary.1.j5sg2t7p8qqh@hornet-10    | <asynchronous suspension>
```

**To Reproduce**
1. Log onto hornet-01
2. `sudo docker service logs -f f55be665-adcb-5487-ab50-cfb5c45bf1df_secondary`

**Expected behavior**
Secondary starts up normally

**Additional context**
Monitoring started to report problems at 0601 UTC 28 Oct 2021

**Comment by murali-shris** [comment]
@cpswan a bunch of users have  reported the same issue
https://github.com/hivedb/hive/issues/263
Some have tried workarounds when hive errors while opening the box.

I tried the below steps in my local to replicate the sequence of changes that we did on prod
1. open normal hive box (in memory) with compaction strategy+encryption. run some updates and deletes
2. open the same box as Lazy with compaction strategy+encryption. run some updates and deletes.
3. open the same box as normal box with encryption but compaction removed.  run some updates and deletes.
I didn't face any issue while opening the box.

Can I get the zip of hive storage from filesystem for @ highvibes.  I can open the box in my local and try if any workaround resolves the issue.

**Comment by cpswan** [comment]
Thanks @murali-shris I'll grab that zip for you.

**Comment by cpswan** [comment]
@murali-shris https://drive.google.com/file/d/1FMFLU1yGehUzZ3RkzfSLJCR9yaSwE5f2/view?usp=sharing

**Comment by cpswan** [comment]
@cconstab just for completeness I tried scaling memory to 300M, but that doesn't help

I've turned it down to 0/0 for now, as it's not serviceable anyway

**Comment by murali-shris** [comment]
@cpswan link to the fixed hive box
https://drive.google.com/drive/u/1/folders/1ae92X1S-mu01VcHk9LQwjwwWGv2zRe0j

**Comment by cpswan** [comment]
@murali-shris I'm going to close this issue, but can you please document how you resolved the storage corruption
