### ISSUE TITLE
Secondary not able to start up with Box errors...

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#370]
**Describe the bug**
Secondary @determinedkitesurfing (2546) for the moment secondary is set to down and off the air...

**To Reproduce**
1 Unknown how this happens but needs investigation

**Expected behavior**
Secondary not to fail in this way.

**Bug logs **

below..

**Additional context**

**Comment by cconstab** [comment]
```
cconstab@hornet-01:~$ docker service logs --tail 10 -f 8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.qxvb8mqt77p8@hornet-10    | #6      HivePersistenceManager.openVault (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:65)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.qxvb8mqt77p8@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.qxvb8mqt77p8@hornet-10    | #7      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:385)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.qxvb8mqt77p8@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.qxvb8mqt77p8@hornet-10    | #8      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.qxvb8mqt77p8@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.qxvb8mqt77p8@hornet-10    | #9      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.qxvb8mqt77p8@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.qxvb8mqt77p8@hornet-10    | #10     main (file:///app/at_secondary_server/bin/main.dart:21)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.qxvb8mqt77p8@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.mfhjmgz4gred@hornet-10    | #6      HivePersistenceManager.openVault (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:65)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.mfhjmgz4gred@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.mfhjmgz4gred@hornet-10    | #7      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:385)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.mfhjmgz4gred@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.mfhjmgz4gred@hornet-10    | #8      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.mfhjmgz4gred@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.mfhjmgz4gred@hornet-10    | #9      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.mfhjmgz4gred@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.mfhjmgz4gred@hornet-10    | #10     main (file:///app/at_secondary_server/bin/main.dart:21)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.mfhjmgz4gred@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.ox4b1jqjdpo3@hornet-10    | #6      HivePersistenceManager.openVault (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:65)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.ox4b1jqjdpo3@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.ox4b1jqjdpo3@hornet-10    | #7      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:385)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.ox4b1jqjdpo3@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.ox4b1jqjdpo3@hornet-10    | #8      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.ox4b1jqjdpo3@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.ox4b1jqjdpo3@hornet-10    | #9      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.ox4b1jqjdpo3@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.ox4b1jqjdpo3@hornet-10    | #10     main (file:///app/at_secondary_server/bin/main.dart:21)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.ox4b1jqjdpo3@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.n19ab0beqeap@hornet-10    | #6      HivePersistenceManager.openVault (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:65)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.n19ab0beqeap@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.n19ab0beqeap@hornet-10    | #7      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:385)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.n19ab0beqeap@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.n19ab0beqeap@hornet-10    | #8      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.n19ab0beqeap@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.n19ab0beqeap@hornet-10    | #9      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.n19ab0beqeap@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.n19ab0beqeap@hornet-10    | #10     main (file:///app/at_secondary_server/bin/main.dart:21)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.n19ab0beqeap@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | INFO|2021-10-30 22:21:34.447834|AtSecondaryServer|currentAtSign : @determinedkitesurfing
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | FINER|2021-10-30 22:21:34.514274|CommitLogKeyStore|last committed sequence: 1473
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | INFO|2021-10-30 22:21:34.514308|CommitLogKeyStore|Keystore initialized successfully
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | INFO|2021-10-30 22:21:34.537820|AccessLogKeyStore|Keystore initialized successfully
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | FINER|2021-10-30 22:21:34.547731|HivePersistenceManager|AtPersistence.init received storagePath: storage/hive
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | FINER|2021-10-30 22:21:34.547765|HivePersistenceManager|getHiveSecretFromFile fetching hiveSecretString for @determinedkitesurfing from file
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | FINER|2021-10-30 22:21:34.547789|HivePersistenceManager|getHiveSecretFromFile found filePath: storage/hive/0432a476b74583b3a0f959195b9ff735727cef915037ea1d76d52012e3f0b6a5.hash
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | AtServer.getHiveSecretFromFile file found
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | FINER|2021-10-30 22:21:34.547975|HivePersistenceManager|AtPersistence.openVault received atsign: @determinedkitesurfing
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | SEVERE|2021-10-30 22:21:35.537471|HivePersistenceManager|AtPersistence().openVault error: HiveError: This should not happen. Please open an issue on GitHub.
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | FINEST|2021-10-30 22:21:35.537545|HivePersistenceManager|scheduleKeyExpireTask starting cron job.
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | SEVERE|2021-10-30 22:21:35.537829|HiveKeystore|HiveKeystore get error: HiveError: Box not found. Did you forget to call Hive.openBox()?
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | Unhandled exception:
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | HiveError: This should not happen. Please open an issue on GitHub.
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #6      HivePersistenceManager.openVault (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:65)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #7      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:385)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #8      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #9      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | #10     main (file:///app/at_secondary_server/bin/main.dart:21)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.srpllpxnju4h@hornet-10    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | INFO|2021-10-30 22:21:43.218744|AtSecondaryServer|currentAtSign : @determinedkitesurfing
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | FINER|2021-10-30 22:21:43.268523|CommitLogKeyStore|last committed sequence: 1473
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | INFO|2021-10-30 22:21:43.268560|CommitLogKeyStore|Keystore initialized successfully
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | INFO|2021-10-30 22:21:43.354744|AccessLogKeyStore|Keystore initialized successfully
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | FINER|2021-10-30 22:21:43.391425|HivePersistenceManager|AtPersistence.init received storagePath: storage/hive
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | FINER|2021-10-30 22:21:43.391471|HivePersistenceManager|getHiveSecretFromFile fetching hiveSecretString for @determinedkitesurfing from file
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | FINER|2021-10-30 22:21:43.391504|HivePersistenceManager|getHiveSecretFromFile found filePath: storage/hive/0432a476b74583b3a0f959195b9ff735727cef915037ea1d76d52012e3f0b6a5.hash
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | AtServer.getHiveSecretFromFile file found
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | FINER|2021-10-30 22:21:43.398510|HivePersistenceManager|AtPersistence.openVault received atsign: @determinedkitesurfing
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | SEVERE|2021-10-30 22:21:44.314453|HivePersistenceManager|AtPersistence().openVault error: HiveError: This should not happen. Please open an issue on GitHub.
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | FINEST|2021-10-30 22:21:44.314513|HivePersistenceManager|scheduleKeyExpireTask starting cron job.
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | SEVERE|2021-10-30 22:21:44.314808|HiveKeystore|HiveKeystore get error: HiveError: Box not found. Did you forget to call Hive.openBox()?
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    |
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | Unhandled exception:
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | HiveError: This should not happen. Please open an issue on GitHub.
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #6      HivePersistenceManager.openVault (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:65)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #7      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:385)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #8      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #9      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | <asynchronous suspension>
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | #10     main (file:///app/at_secondary_server/bin/main.dart:21)
8866752b-71d7-5ea2-87fe-c63b9750bc17_secondary.1.btej94qljkv1@hornet-06    | <asynchronous suspension>
^C
```

**Comment by cpswan** [comment]
Secondary is back online
