### ISSUE TITLE
HiveError on @daily3bossanova 

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#377]
**Describe the bug**

```
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    | INFO|2021-11-03 09:36:10.440626|AtSecondaryServer|currentAtSign : @daily3bossanova
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | AtServer.getHiveSecretFromFile file found
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    | FINER|2021-11-03 09:36:10.538588|CommitLogKeyStore|last committed sequence: 3058
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | FINER|2021-11-03 09:35:41.566722|HivePersistenceManager|AtPersistence.openVault received atsign: @daily3bossanova
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    | INFO|2021-11-03 09:36:10.538655|CommitLogKeyStore|Keystore initialized successfully
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | SEVERE|2021-11-03 09:35:43.237791|HivePersistenceManager|AtPersistence().openVault error: HiveError: This should not happen. Please open an issue on GitHub.
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    | INFO|2021-11-03 09:36:10.651550|AccessLogKeyStore|Keystore initialized successfully
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | FINEST|2021-11-03 09:35:43.237858|HivePersistenceManager|scheduleKeyExpireTask starting cron job.
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    | FINER|2021-11-03 09:36:10.853829|HivePersistenceManager|AtPersistence.init received storagePath: storage/hive
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | SEVERE|2021-11-03 09:35:43.238158|HiveKeystore|HiveKeystore get error: HiveError: Box not found. Did you forget to call Hive.openBox()?
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    | FINER|2021-11-03 09:36:10.853896|HivePersistenceManager|getHiveSecretFromFile fetching hiveSecretString for @daily3bossanova from file
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    | FINER|2021-11-03 09:36:10.853933|HivePersistenceManager|getHiveSecretFromFile found filePath: storage/hive/2323a04ddaf5c20e7cb1bdd7fe8be29d78c00fe5fb3a418aad9ce07dac9fe61e.hash
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | Unhandled exception:
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | HiveError: This should not happen. Please open an issue on GitHub.
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    | AtServer.getHiveSecretFromFile file found
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    | FINER|2021-11-03 09:36:10.854232|HivePersistenceManager|AtPersistence.openVault received atsign: @daily3bossanova
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | <asynchronous suspension>
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.xv2k2epkejgr@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | <asynchronous suspension>
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | <asynchronous suspension>
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #5      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | <asynchronous suspension>
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #6      HivePersistenceManager.openVault (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:65)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | <asynchronous suspension>
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #7      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:385)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | <asynchronous suspension>
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #8      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | <asynchronous suspension>
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #9      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | <asynchronous suspension>
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | #10     main (file:///app/at_secondary_server/bin/main.dart:21)
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.3h9g35f7bdok@hornet-04    | <asynchronous suspension>
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.ma8u3nnvh9u8@hornet-04    | INFO|2021-11-03 09:36:00.496457|AtSecondaryServer|currentAtSign : @daily3bossanova
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.ma8u3nnvh9u8@hornet-04    |
a969e972-fa7d-5b2d-a1f1-ad7675de5c43_secondary.1.ma8u3nnvh9u8@hornet-04    | FINER|2021-11-03 09:36:00.572724|CommitLogKeyStore|last committed sequence: 3058
```

**Additional context**

First reported by monitoring at 0930UTC 3 Nov 2021

**Comment by murali-shris** [comment]
fixed and uploaded the recovered box in gdrive

**Comment by cpswan** [comment]
secondary is back up

**Comment by cpswan** [comment]
Reopening this for philosophical75

@murali-shris I've shared the storage directory with you

**Comment by cpswan** [comment]
philosophical75 secondary is back up
