### ISSUE TITLE
Unable to login or setup a new device with @ai6bh

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#451]
**Describe the bug**
New device is unable to check @sign and yet it is up and replies to scans. Existing devices cannot connect either

**To Reproduce**
1. Connect with CATWEB or any other @ app
2. Then look at log files and screen 

**Expected behavior**

**Screenshots**

Log files
```
bd41411-f881-5732-852e-aa53a97ba739_secondary.1.iyuakmq7fv9n@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.iyuakmq7fv9n@hornet-11    | SEVERE|2021-12-25 21:58:37.860479|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.iyuakmq7fv9n@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.flicwi89a3jk@hornet-11    | SEVERE|2021-12-26 01:21:04.970892|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.flicwi89a3jk@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.flicwi89a3jk@hornet-11    | SEVERE|2021-12-26 01:21:06.153866|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.flicwi89a3jk@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.flicwi89a3jk@hornet-11    | SEVERE|2021-12-26 01:21:06.457282|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.flicwi89a3jk@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.flicwi89a3jk@hornet-11    | SEVERE|2021-12-26 01:21:10.971835|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.flicwi89a3jk@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.flicwi89a3jk@hornet-11    | SEVERE|2021-12-26 01:21:13.691853|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.flicwi89a3jk@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.g262fdodafva@hornet-11    | #7      AtCommitLogManagerImpl.getCommitLog (package:at_persistence_secondary_server/src/log/commitlog/at_commit_log_manager_impl.dart:27)
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.g262fdodafva@hornet-11    | <asynchronous suspension>
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.g262fdodafva@hornet-11    | #8      AtSecondaryServerImpl._initializeHiveInstances (package:at_secondary/src/server/at_secondary_impl.dart:359)
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.g262fdodafva@hornet-11    | <asynchronous suspension>
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.g262fdodafva@hornet-11    | #9      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:135)
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.g262fdodafva@hornet-11    | <asynchronous suspension>
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.g262fdodafva@hornet-11    | #10     SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.g262fdodafva@hornet-11    | <asynchronous suspension>
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.g262fdodafva@hornet-11    | #11     main (file:///app/at_secondary_server/bin/main.dart:21)
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.g262fdodafva@hornet-11    | <asynchronous suspension>
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.4dzdyf37fx85@hornet-11    | SEVERE|2021-12-26 01:22:39.797477|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.4dzdyf37fx85@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.4dzdyf37fx85@hornet-11    | SEVERE|2021-12-26 01:22:40.238684|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.4dzdyf37fx85@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.4dzdyf37fx85@hornet-11    | SEVERE|2021-12-26 01:22:47.170305|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.4dzdyf37fx85@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.4dzdyf37fx85@hornet-11    | SEVERE|2021-12-26 01:22:48.200860|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.4dzdyf37fx85@hornet-11    | 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.4dzdyf37fx85@hornet-11    | SEVERE|2021-12-26 01:22:48.479530|AtSecondaryServer|HandshakeException: Connection terminated during handshake 
1bd41411-f881-5732-852e-aa53a97ba739_secondary.1.4dzdyf37fx85@hornet-11    | 
```

**Smartphone (please complete the following information):**
 - Anything

**Were you using an @‎application when the bug was found?**
  - CATWEB

**Additional context**

**Comment by cconstab** [comment]
So this is the certificate not any keys.. The cert did not renew and is timed out as of the 24th Dec.. Are there anmy more ???

Colin


```
-----BEGIN CERTIFICATE-----
MIIGvDCCBKSgAwIBAgIQXwVr6ioqQw6ILfkQBi09VTANBgkqhkiG9w0BAQwFADBL
MQswCQYDVQQGEwJBVDEQMA4GA1UEChMHWmVyb1NTTDEqMCgGA1UEAxMhWmVyb1NT
TCBSU0EgRG9tYWluIFNlY3VyZSBTaXRlIENBMB4XDTIxMDkyNTAwMDAwMFoXDTIx
MTIyNDIzNTk1OVowQjFAMD4GA1UEAxM3MWJkNDE0MTEtZjg4MS01NzMyLTg1MmUt
YWE1M2E5N2JhNzM5Lmhvcm5ldC5hdHNpZ24uem9uZTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAMIiU08gY7tKp8TzF2/94/h7xR1jGnhzbt5nomrs5PKC
IjEFBb5D/400A7f4eUL4yd9FH39juQ01cmz9BrPecUvfBdyg2qR9JkIO5Dw3jsxj
c1Soof/IJt4O2nK8VxOoQM0H14W2HWJpYe9IsyjFMNcCGGO31qpOQ0U5adV4ZHET
XuIDRaWadzkL9ja05rqLZBMLuNjd8qT3wayJcwad5sU6SHFKKgaGTvDPMlAhPP4K
mdxwCwcQSesLRFaqNVowAiwNp4OstB+O/J3EI0SeSbOwmi9BMD29PK9mADq0SVwL
Lg5HpWbV63s1KL20cWsaqWkQVEZe5FrxfHj4aS3DXqMCAwEAAaOCAqMwggKfMB8G
A1UdIwQYMBaAFMjZeGii2Rlo1T1y3l8KPty1hoamMB0GA1UdDgQWBBQfBDmmknie
6nkJtWHlhTcVX28/mTAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNV
HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwSQYDVR0gBEIwQDA0BgsrBgEEAbIx
AQICTjAlMCMGCCsGAQUFBwIBFhdodHRwczovL3NlY3RpZ28uY29tL0NQUzAIBgZn
gQwBAgEwgYgGCCsGAQUFBwEBBHwwejBLBggrBgEFBQcwAoY/aHR0cDovL3plcm9z
c2wuY3J0LnNlY3RpZ28uY29tL1plcm9TU0xSU0FEb21haW5TZWN1cmVTaXRlQ0Eu
Y3J0MCsGCCsGAQUFBzABhh9odHRwOi8vemVyb3NzbC5vY3NwLnNlY3RpZ28uY29t
MIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYAfT7y+I//iFVoJMLAyp5SiXkrxQ54
CX8uapdomX4i8NcAAAF8HpD9ZwAABAMARzBFAiEA2GiqGumLn8xNkpcWQpQ7UfTG
YrDRID+ofV33yOt5UagCICUyvRBylbKvmVyZQjSe29sidXR+10M++X6tN2LpT2gb
AHYARJRlLrDuzq/EQAfYqP4owNrmgr7YyzG1P9MzlrW2gagAAAF8HpD9QwAABAMA
RzBFAiA+SeE1LJSXZVBmg7VwcxA5ThsaUAHJehjAT0S+FfsmRwIhAPRpA4EVf70O
YqmhxTBmoR/jvJK47FkOZcK18JLIuwQrMEIGA1UdEQQ7MDmCNzFiZDQxNDExLWY4
ODEtNTczMi04NTJlLWFhNTNhOTdiYTczOS5ob3JuZXQuYXRzaWduLnpvbmUwDQYJ
KoZIhvcNAQEMBQADggIBAG6/e/szyubq91WktUO8Q/eoW9f5Xedr4/v4xi2ww9v8
J8jrHxHk1vYLhvLMNHEIRJKvEVaFZvWYKgnxJxirw8mk0zfzBsxOh8HBHAiJiO92
+EbrVp9QsqXR5dg+r0Du7//tRdVM6glLUpbF4FJwezuU5eQHBfaPVH3moeU4+HZI
Q+TfGlvue4c0jJ1/06VDbch0a1WKQdqTqHxCyTXqBsmwWWb/9K7hjJbhq05EZgQN
hO0/7NRD0MlsJ6ZfnX++/FE0x1HAcyse+ccTQKLcZl4tqXYZJ1/lh2FDTYHpnqnj
dtGhvuqNTe42dDbrX8AUaFtsKmPmkRINkRpcCX1F9cpx9EKJYVEIBsjw3SH5gx3W
Undq9/LXuYBx4nbN/2Toq2U+s8TsC4DeJFtiuP7fwDKoRSn+hvNiOrjWMA8vE/bQ
6mfFjBfAqnHXE4VT7ylam7gJ1+CT9UFfugauU6/yQS8uNGc0VaRkzPGiMI3xaigP
4Qya4ocWUOHpFu+Mkqu9N6Zw3zBGtOMQGHlSSZUgzcSA5V1vDasXkx4K/ivff5Y8
f30OWv494CIKmE06MmgJfrwovnUfBLd7wWhZMdaWvitMrySiXRk77XIS8nD8D15f
8seFE10SjEGY+QK/44XEWGQeRmkOshR/bebvZtIoSB6MVoSqgjynUT/K8yz9rYbe
-----END CERTIFICATE-----
```

**Comment by cconstab** [comment]
This was an error with certificates.. Narendra fixed.. Needs documentation of cert renewal process..

**Comment by athandle** [comment]
SSL renewed
@cconstab  can we close this?

**Comment by kumarnarendra701** [comment]
@cconstab - Somehow new cronjob was not there on root user crontab but now I have added cronjob for renewal.
On Prod -
08 07 * * * cd /gluster/@/api/ && /gluster/@/api/cert_ren.sh

**Comment by kumarnarendra701** [comment]
@cconstab @cpswan @athandle  - Please check and confirm if we can close this.

**Comment by athandle** [comment]
@cconstab  can we close this?
