### ISSUE TITLE
Of the 1 these are the first few effected @signs,  @jetskiracinghistoric1 (3493), 

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#452]
**Describe the bug**
This atsign is having  an issue with Keys/Hivedb 
**To Reproduce**
Issue is on production Hornet cluster

**Expected behavior**
run without errors

**Screenshots**
```
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | AtServer.getHiveSecretFromFile file found
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | SEVERE|2021-12-28 06:10:56.650062|HivePersistenceManager|AtPersistence().init error: HiveError: This should not happen. Please open an issue on GitHub. 
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | 
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | Unhandled exception:
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | HiveError: This should not happen. Please open an issue on GitHub.
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:250)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #1      _KeyReader.readKeys (package:hive/src/io/frame_io_helper.dart:73)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #2      FrameIoHelper.keysFromFile (package:hive/src/io/frame_io_helper.dart:32)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:88)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #4      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #5      HiveImpl.openLazyBox (package:hive/src/hive_impl.dart:156)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #6      HiveBase.openBox (package:at_persistence_secondary_server/src/keystore/hive_base.dart:24)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #7      HivePersistenceManager.initialize (package:at_persistence_secondary_server/src/keystore/hive_manager.dart:39)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #8      HiveBase.init (package:at_persistence_secondary_server/src/keystore/hive_base.dart:15)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #9      AtSecondaryServerImpl._initializePersistentInstances (package:at_secondary/src/server/at_secondary_impl.dart:396)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #10     AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:136)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #11     SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | #12     main (file:///app/at_secondary_server/bin/main.dart:21)
099b3387-7c74-5c1a-a0d3-25d834489bac_secondary.1.r6qjcksrysrq@hornet-06    | <asynchronous suspension>
```

**Comment by cconstab** [comment]
The secondary for the moment is turned down so we do not get errors every 15 mins reported..

`docker service scale 099b3387-7c74-5c1a-a0d3-25d834489bac_secondary=0`

**Comment by murali-shris** [comment]
fix hive issue for philosophical75 as well

**Comment by cpswan** [comment]
jetskiracinghistoric1 and philosophical75 have been restored
