### ISSUE TITLE
Too many cert renewals are failing over to ZeroSSL

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#545]
**Describe the bug**
The Production Issues chat channel is littered with messages like:

```
Warning - LetsEncrypt SSL not generating failing over to ZeroSSL(UUID - ffb1667b-fd2f-5f09-b659-e233a907a242)
```

Many of these messages actually relate to the Buzz environment and are in the wrong channel, hence https://github.com/atsign-company/secondaries-scripts/issues/20

Looking at logs this seems to happen when LetsEncrypt failes to respond:

```
2022-03-06 22:20:44,338:INFO:Request to the ACME server an order to validate domains.
Traceback (most recent call last):
  File "/gluster/@/api/acme_certs.py", line 413, in <module>
    main(sys.argv[1:])
  File "/gluster/@/api/acme_certs.py", line 399, in main
    signed_crt = get_crt(config, LOGGER)
  File "/gluster/@/api/acme_certs.py", line 225, in get_crt
    http_response, order = _send_signed_request(acme_config["newOrder"], new_order)
  File "/gluster/@/api/acme_certs.py", line 138, in _send_signed_request
    raise RuntimeError("Unable to get response from ACME server.")
RuntimeError: Unable to get response from ACME server.
Failing over to ZeroSSL
```

or when LetsEncrypt is unable to verify DNS:

```
Traceback (most recent call last):
  File "/gluster/@/api/acme_certs.py", line 413, in <module>
    main(sys.argv[1:])
  File "/gluster/@/api/acme_certs.py", line 399, in main
    signed_crt = get_crt(config, LOGGER)
  File "/gluster/@/api/acme_certs.py", line 294, in get_crt
    raise ValueError("Challenge for domain {0} did not pass: {1}".format(
ValueError: Challenge for domain 44b8bc82-d737-5996-a770-ea514e1b29e9.buzz.do-sf2.atsign.zone did not pass: {'type': 'dns-01', 'status': 'invalid', 'error': {'type': 'urn:ietf:params:acme:error:dns', 'detail': 'DNS problem: NXDOMAIN looking up TXT for _acme-challenge.44b8bc82-d737-5996-a770-ea514e1b29e9.buzz.do-sf2.atsign.zone - check that a DNS record exists for this domain', 'status': 400}, 'url': 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/79719141250/024atQ', 'token': 'f4VJ69P0PsVWOV2cVIUezUATxbzzWNozV69r7hWle4Y', 'validated': '2022-02-18T11:14:26Z'}
Failing over to ZeroSSL
```

**Expected behavior**
Script copes with intermittent failures of services more gracefully.

**Comment by cpswan** [comment]
https://github.com/atsign-company/secondaries-scripts/pull/23 awaiting review by @cconstab or @kumarnarendra701
