### ISSUE TITLE
Error on start up of secondary without config.yaml

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#91]
When starting the secondary from the command line without the config/config.yaml file in place I get the error below.. I believe the default value for **notificationQuarantineDuration** should be put in place if the config.yaml is not found like the other values.

 This could I think prevent the secondary starting up in some enviroments..

With no config.yaml in place

```secondary_1  | INFO|2021-04-16 01:29:17.087748|AtSecondaryServer|currentAtSign : @colin
secondary_1  |
secondary_1  | FINER|2021-04-16 01:29:17.092662|CommitLogKeyStore|last committed sequence: 1
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:29:17.100245|HivePersistenceManager|scheduleKeyExpireTask starting cron job.
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:29:17.101842|HiveKeystore|hive key:privatekey:at_secret
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:29:17.103237|HiveKeystore|hive value:AtData{data: 1234567890qwertyuio, metaData: {createdBy: null, updatedBy: null, createdAt: 2021-04-16 01:29:17.101832Z, updatedAt: 2021-04-16 01:29:17.101832Z, availableAt: null, expiresAt: null, refreshAt: null, status: active, version: 0, ttl: null, ttb: null, ttr: null, ccd: null, isBinary: null, isEncrypted: null, dataSignature: null}
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:29:17.105754|AtRefreshJob|scheduleKeyRefreshTask runs at 6 hours
secondary_1  |
secondary_1  | Unhandled exception:
secondary_1  | NoSuchMethodError: The method '[]' was called on null.
secondary_1  | Receiver: null
secondary_1  | Tried calling: []()
secondary_1  | #0      AtSecondaryConfig.notificationQuarantineDuration (package:at_secondary/src/server/at_secondary_config.dart:544)
secondary_1  | #1      new ResourceManager._internal (package:at_secondary/src/notification/resource_manager.dart:25)
secondary_1  | #2      ResourceManager._singleton (package:at_secondary/src/notification/resource_manager.dart:13)
secondary_1  | #3      new ResourceManager.getInstance (package:at_secondary/src/notification/resource_manager.dart)
secondary_1  | #4      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:173)
secondary_1  | <asynchronous suspension>
secondary_1  | #5      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
secondary_1  | <asynchronous suspension>
secondary_1  | #6      main (file:///buddy/atsign-open-source/at_secondary/at_secondary_server/bin/main.dart:21)
secondary_1  | <asynchronous suspension>
```

But putting the file in place the secondary starts up just fine. 

```secondary_1  | INFO|2021-04-16 01:31:17.777855|AtSecondaryServer|currentAtSign : @colin
secondary_1  |
secondary_1  | FINER|2021-04-16 01:31:17.780268|CommitLogKeyStore|last committed sequence: 1
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:31:17.787286|HivePersistenceManager|scheduleKeyExpireTask starting cron job.
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:31:17.787542|HiveKeystore|hive key:privatekey:at_secret
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:31:17.787573|HiveKeystore|hive value:AtData{data: 1234567890qwertyuio, metaData: {createdBy: null, updatedBy: null, createdAt: 2021-04-16 01:31:17.787533Z, updatedAt: 2021-04-16 01:31:17.787533Z, availableAt: null, expiresAt: null, refreshAt: null, status: active, version: 0, ttl: null, ttb: null, ttr: null, ccd: null, isBinary: null, isEncrypted: null, dataSignature: null}
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:31:17.788265|AtRefreshJob|scheduleKeyRefreshTask runs at 14 hours
secondary_1  |
```

**Comment by cconstab** [comment]
On further looking the docker container includes the /atsign/config/config.yaml so that saves the day. But without the config file in the container (I have overlaid the /atsign directory) by using a volume the defaults values should still be in place if memory serves.
